In [1]:
import numpy as np
import pandas as pd
from matplotlib.pyplot import subplots
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor as VIF
from statsmodels.stats.anova import anova_lm
from ISLP import load_data
from ISLP.models import ModelSpec as MS, summarize, poly
from sklearn.linear_model import LinearRegression

# Simple Linear Regression Using Boston Real Estate Data

In [2]:
boston = load_data('Boston')
boston.columns

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'lstat', 'medv'],
      dtype='object')

In [3]:
x = pd.DataFrame({'intercept': np.ones(boston.shape[0]),
                 '% of marginalized population': boston['lstat']})
x.head(), x.shape

(   intercept  % of marginalized population
 0        1.0                          4.98
 1        1.0                          9.14
 2        1.0                          4.03
 3        1.0                          2.94
 4        1.0                          5.33,
 (506, 2))

In [4]:
y = pd.DataFrame({'Median Home Value': boston['medv']})
y.head(), y.shape

(   Median Home Value
 0               24.0
 1               21.6
 2               34.7
 3               33.4
 4               36.2,
 (506, 1))

In [5]:
model = sm.OLS(y, x)
results = model.fit()
summarize(results)

                                 coef  std err       t  P>|t|
intercept                     34.5538    0.563  61.415    0.0
% of marginalized population  -0.9500    0.039 -24.528    0.0

In [6]:
results.params

intercept                       34.553841
% of marginalized population    -0.950049
dtype: float64

In [7]:
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:      Median Home Value   R-squared:                       0.544
Model:                            OLS   Adj. R-squared:                  0.543
Method:                 Least Squares   F-statistic:                     601.6
Date:                Thu, 21 May 2026   Prob (F-statistic):           5.08e-88
Time:                        10:32:23   Log-Likelihood:                -1641.5
No. Observations:                 506   AIC:                             3287.
Df Residuals:                     504   BIC:                             3295.
Df Model:                           1
Covariance Type:            nonrobust
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
intercept                       34.5538      0.563     61.415      0.000      33.448      35.659
% of marginalized population    -0.9500      0.039    -24.528      0.000      -1.026      -0.874
==============================================================================
Omnibus:                      137.043   Durbin-Watson:                   0.892
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              291.373
Skew:                           1.453   Prob(JB):                     5.36e-64
Kurtosis:                       5.319   Cond. No.                         29.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

# Multiple Linear Regression

In [9]:
x = MS(['lstat', 'age']).fit_transform(boston)
model = sm.OLS(y, x)
result = model.fit()
summarize(result)

              coef  std err       t  P>|t|
intercept  33.2228    0.731  45.458  0.000
lstat      -1.0321    0.048 -21.416  0.000
age         0.0345    0.012   2.826  0.005